Repository SkarabeyDM/graphiql-app, pull requests merged in 2024-09, with the labels that each got.

#40 Sprint 2 feat/auth register pages
  app/login/layout.tsx
  app/login/page.tsx
  app/register/layout.tsx
  app/register/page.tsx
  src/app/layout/ui/CenterLayout.tsx
  src/app/layout/ui/RootLayout.tsx
  src/app/layout/ui/index.ts
  src/entities/user/index.ts
  src/entities/user/model/firebase.ts
  src/entities/user/ui/PrivateRoute.tsx
  src/features/auth/index.ts
  src/features/auth/ui/LogoutButton.tsx
  src/features/auth/ui/index.ts
  src/pages/HomePage/ui/HomePage.tsx
  src/pages/HomePage/ui/index.ts
  src/pages/LoginPage/index.ts
  src/pages/LoginPage/ui/LoginPage.tsx
  src/pages/LoginPage/ui/index.ts
  src/pages/RegisterPage/index.ts
  src/pages/RegisterPage/ui/RegisterPage.tsx
  src/pages/RegisterPage/ui/index.ts
  src/shared/tests/__tests__/Login.test.tsx
  src/shared/tests/__tests__/Logout.test.tsx
  src/shared/tests/__tests__/Registration.test.tsx
  src/shared/tests/__tests__/VisibilityButton.test.tsx
  src/shared/ui/Form.tsx
  src/shared/ui/Link.tsx
  src/shared/ui/PasswordInput.tsx
  src/shared/ui/TextFieldHint.tsx
  src/shared/ui/index.ts
  src/widgets/alert/ui/Alert.tsx
  src/widgets/authorization/Authorisation.component.tsx
  src/widgets/authorization/model/authorization.model.ts
  src/widgets/authorization/ui/Login.tsx
  src/widgets/authorization/ui/LoginForm.tsx
  src/widgets/authorization/ui/Logout.tsx
  src/widgets/authorization/ui/RegisterForm.tsx
  src/widgets/authorization/ui/Registration.tsx
  src/widgets/authorization/ui/VisibilityButton.tsx
  src/widgets/authorization/ui/index.ts
Labels: ➕ Feature, 🎨 Style, 🛠️ Refactor

#41 Sprint 2 feat/rest full client
  next.config.mjs
  package-lock.json
  package.json
  src/pages/RestFullClientPage/index.ts
  src/pages/RestFullClientPage/ui/RestFullClientPage.tsx
  src/pages/RestFullClientPage/ui/index.ts
  src/shared/redux/slices/alertSlice.ts
  src/shared/tests/__tests__/BodyManager.test.tsx
  src/shared/tests/__tests__/HeaderManager.test.tsx
  src/shared/tests/__tests__/HomePage.test.tsx
  src/shared/tests/__tests__/Login.test.tsx
  src/shared/tests/__tests__/Logout.test.tsx
  src/shared/tests/__tests__/MethodManager.test.tsx
  src/shared/tests/__tests__/OneHeaderElement.test.tsx
  src/shared/tests/__tests__/Registration.test.tsx
  src/shared/tests/__tests__/UrlManager.test.tsx
  src/shared/tests/__tests__/encodeBase64.test.ts
  src/shared/tests/__tests__/redux.test.ts
  src/shared/tests/__tests__/requestHandler.test.ts
  src/widgets/restFullClient/index.ts
  src/widgets/restFullClient/lib/encodeBase64.ts
  src/widgets/restFullClient/lib/requestHandler.ts
  src/widgets/restFullClient/model/bodyManagerModel.ts
  src/widgets/restFullClient/model/headerManagerModel.ts
  src/widgets/restFullClient/model/methodManagerModel.ts
  src/widgets/restFullClient/model/requestHandlerModel.ts
  src/widgets/restFullClient/model/schema.ts
  src/widgets/restFullClient/model/urlManagerModel.ts
  src/widgets/restFullClient/ui/BodyManager.tsx
  src/widgets/restFullClient/ui/HeaderManager.tsx
  src/widgets/restFullClient/ui/MethodManager.tsx
  src/widgets/restFullClient/ui/OneHeaderElement.tsx
  src/widgets/restFullClient/ui/RestFullClient.tsx
  src/widgets/restFullClient/ui/UrlManager.tsx
  src/widgets/restFullClient/ui/index.ts
Labels: 🖥️ Environment, ➕ Feature

#45 Sprint 3 feat/internationalization
  app/[locale]/layout.tsx
  app/[locale]/login/layout.tsx
  app/[locale]/login/page.tsx
  app/[locale]/page.tsx
  app/[locale]/register/layout.tsx
  app/[locale]/register/page.tsx
  app/favicon.ico
  messages/en.json
  messages/ru.json
  middleware.ts
  next.config.mjs
  package-lock.json
  package.json
  src/app/layout/ui/RootLayout.tsx
  src/features/auth/ui/LogoutButton.tsx
  src/features/internationalization/index.ts
  src/features/internationalization/ui/LanguageSelect.tsx
  src/features/internationalization/ui/index.ts
  src/global.d.ts
  src/shared/i18n/index.ts
  src/shared/i18n/locales.ts
  src/shared/i18n/messages.ts
  src/shared/i18n/request.ts
  src/shared/i18n/routing.ts
  src/shared/tests/__tests__/HomePage.test.tsx
  src/shared/tests/__tests__/Login.test.tsx
  src/shared/tests/__tests__/Registration.test.tsx
  src/shared/tests/lib/renderWithProviders.tsx
  src/shared/ui/Link.tsx
  src/widgets/authorization/ui/LoginForm.tsx
  src/widgets/authorization/ui/RegisterForm.tsx
  tsconfig.json
Labels: 🖥️ Environment, ➕ Feature, 🔎 Need review

#50 Sprint 4 feat/main page
  messages/en.json
  messages/ru.json
  src/app/layout/ui/RootLayout.tsx
  src/features/editor/index.ts
  src/features/editor/ui/EditorsGroup.tsx
  src/features/editor/ui/index.ts
  src/pages/HomePage/ui/HomePage.tsx
  src/pages/RestFullClientPage/ui/RestFullClientPage.tsx
  src/shared/tests/__tests__/HomePage.test.tsx
  src/shared/ui/Button.tsx
  src/shared/ui/PasswordInput.tsx
  src/shared/ui/index.ts
  src/widgets/Authors/index.ts
  src/widgets/Authors/ui/AuthorCard.tsx
  src/widgets/Authors/ui/Authors.tsx
  src/widgets/Authors/ui/index.ts
  src/widgets/Footer/ui/Footer.tsx
  src/widgets/Greeting/index.ts
  src/widgets/Greeting/lib/getUserName.ts
  src/widgets/Greeting/lib/index.ts
  src/widgets/Greeting/ui/Greeting.tsx
  src/widgets/Greeting/ui/index.ts
  src/widgets/Header/ui/Header.tsx
  src/widgets/restFullClient/ui/RestFullClient.tsx
Labels: ➕ Feature, 🔎 Need review, 🎨 Style

#48 Sprint 3 feat/graph ql
  app/[locale]/editor/graphiql/page.tsx
  package-lock.json
  package.json
  src/features/editor/lib/encodeBase64.ts
  src/features/editor/model/headersEditorModel.ts
  src/features/editor/model/methodEditorModel.ts
  src/features/editor/model/schema.ts
  src/features/editor/model/urlEditorModel.ts
  src/features/editor/ui/HeaderEditor.tsx
  src/features/editor/ui/MethodEditor.tsx
  src/features/editor/ui/OneHeaderElement.tsx
  src/features/editor/ui/UrlEditor.tsx
  src/features/editor/ui/index.ts
  src/pages/GraphQlPage/index.ts
  src/pages/GraphQlPage/ui/GraphQlPage.tsx
  src/pages/GraphQlPage/ui/index.ts
  src/shared/lib/requestHandler.ts
  src/shared/tests/__tests__/HeaderEditor.test.tsx
  src/shared/tests/__tests__/MethodEditor.test.tsx
  src/shared/tests/__tests__/OneHeaderElement.test.tsx
  src/shared/tests/__tests__/UrlEditor.test.tsx
  src/shared/tests/__tests__/encodeBase64.test.ts
  src/shared/tests/__tests__/requestHandler.test.ts
  src/widgets/graphQl/index.ts
  src/widgets/graphQl/model/bodyEditorModel.ts
  src/widgets/graphQl/model/graphqlPrettier.d.ts
  src/widgets/graphQl/ui/BodyEditor.tsx
  src/widgets/graphQl/ui/GraphQl.tsx
  src/widgets/graphQl/ui/index.ts
  src/widgets/restFullClient/model/requestHandlerModel.ts
  src/widgets/restFullClient/model/urlManagerModel.ts
  src/widgets/restFullClient/ui/RestFullClient.tsx
  tsconfig.json
Labels: 🖥️ Environment, ➕ Feature

#54 Sprint 4 refactor/translation
  messages/en.json
  messages/ru.json
  src/entities/user/ui/PrivateRoute.tsx
  src/features/editor/lib/examples.json
  src/features/editor/lib/index.ts
  src/features/editor/model/headersEditorModel.ts
  src/features/editor/ui/HeaderEditor.tsx
  src/features/editor/ui/MethodEditor.tsx
  src/features/editor/ui/OneHeaderElement.tsx
  src/features/editor/ui/UrlEditor.tsx
  src/shared/tests/__tests__/HeaderEditor.test.tsx
  src/widgets/graphQl/model/bodyEditorModel.ts
  src/widgets/graphQl/ui/BodyEditor.tsx
  src/widgets/graphQl/ui/GraphQl.tsx
  src/widgets/restFullClient/ui/RestFullClient.tsx
Labels: ➕ Feature, 🛠️ Refactor
