Repository SkarabeyDM/graphiql-app, pull requests merged in 2024-08, with the labels that each got.

#5 Sprint 1 init/setup project
  .eslintrc.json
  .gitignore
  .husky/pre-commit
  .husky/pre-push
  .prettierrc
  README.md
  __tests__/Home.test.tsx
  app/favicon.ico
  app/globals.scss
  app/layout.tsx
  app/page.module.scss
  app/page.tsx
  jest.config.ts
  jest.setup.ts
  next.config.mjs
  package-lock.json
  package.json
  tsconfig.json
Labels: Environment, Feature, Approved

#18 fix: fix project configuration
  .eslintignore
  app/layout.tsx
  app/page.tsx
  package-lock.json
  package.json
Labels: Bug fix, Environment, Approved

#20 FSD конфигурация
  pages/README.md
  tsconfig.json
Labels: Environment, 💹 Approved

#22 Переезд на MUI
  app/globals.scss
  app/layout.tsx
  app/page.module.scss
  app/page.tsx
  package-lock.json
  package.json
Labels: Environment, 💹 Approved

#23 config: change PR template
  .github/pull_request_template.md
Labels: 🖥️ Environment, ✔️ Approved

#25 refactor: move `HomePage` and `RootLayout` to FSD-layers
  app/layout.tsx
  app/page.tsx
  src/app/layout/ui/RootLayout.tsx
  src/pages/HomePage/index.ts
  src/pages/HomePage/ui/HomePage.tsx
  src/pages/HomePage/ui/index.ts
Labels: ✔️ Approved, 🛠️ Refactor

#28 Добавление фавикона
  app/favicon.ico
  public/assets/favicon.ico
  src/app/layout/ui/RootLayout.tsx
Labels: ✔️ Approved

#32 fix: fix alert component
  src/widgets/alert/ui/Alert.tsx
Labels: ✔️ Approved, 🛠️ Fix

#34 Sprint 2 refactor/store provider
  src/app/layout/ui/RootLayout.tsx
  src/shared/redux/StoreProvider.tsx
  src/shared/redux/hooks.ts
  src/shared/redux/index.ts
  src/shared/redux/store.ts
  src/shared/tests/__tests__/HomePage.test.tsx
  src/shared/tests/__tests__/Login.test.tsx
  src/shared/tests/__tests__/Logout.test.tsx
  src/shared/tests/__tests__/Registration.test.tsx
  src/shared/tests/__tests__/VisibilityButton.test.tsx
  src/shared/tests/__tests__/redux.test.ts
  src/shared/tests/lib/index.ts
  src/shared/tests/lib/renderWithProviders.tsx
  src/widgets/alert/ui/Alert.tsx
  src/widgets/authorization/Authorisation.component.tsx
  src/widgets/authorization/ui/Login.tsx
  src/widgets/authorization/ui/Logout.tsx
  src/widgets/authorization/ui/Registration.tsx
Labels: ✔️ Approved, 🛠️ Refactor, 🛠️ Fix
